### ISSUE TITLE
Identify feature gaps with vanilla Dependency-Track

### ISSUE THREAD

**Issue by nscuro** [DependencyTrack/hyades#373]
We refactored and restructured a lot of things in the API server to make it work with Hyades.

It is possible that by doing this we removed or broke certain features (currently: policy evaluation is not happening).

This macro issue is for identifying more of those gaps and documenting them.

### Areas to investigate

* Vulnerability analysis after BOM upload
* Policy evaluation after BOM upload
* Recurring daily vulnerability analysis
* Recurring policy evaluation
* Metrics calculation
* Repository meta analysis
* Vulnerability mirroring
* Notification publishing
  * Test with actual external services (MS Teams)
* ...

### Known Gaps

- [x] ~Only supports PostgreSQL for now, will need to support MSSQL and MySQL as well~
   * Issue raised:  #642
- [x] ~`NEW_VULNERABLE_DEPENDENCY` notification doesn't work~
   * Issue raised:  #643
- [x] ~Policy evaluation is not triggered~
   * Re-implemented
- [x] ~Completion of repository meta analysis can not be tracked~
   * Support for this in upstream is rudimentary and currently not used, but will be needed for some use cases in the future
   * Issue raised: #644
- [x] ~Mirroring and ad-hoc vulnerability analysis with VulnDB is not implemented~
   * Issue raised: #286
- [x] ~Mirroring of GitHub Advisories is not yet implemented~
   * Re-implemented
- [x] ~`BOM_CONSUMED`, `BOM_PROCESSED`, `VEX_CONSUMED`, and `VEX_PROCESSED` notifications do not contain the original CycloneDX BOM / VEX~
   * Due to size limitations of Kafka events; BOMs and VEXes can be arbitrarily large
   * Once we integrate with BOM repo server we can link to it (#633)
   * Issue raised: #646
- [x] ~Fuzzy analysis with internal analyzer doesn't work~
   * The feature relies on Lucene indexes, which the vulnerability analyzer does not have access to
   * Issue raised: #645
- [x] ~Jira notifications don't work (#424)~

**Comment by nscuro** [comment]
### Known Gaps

- [ ] `NEW_VULNERABLE_DEPENDENCY` notification doesn't work
  * Must be evaluated after vulnerability scan after BOM upload completed
- [ ] Policy evaluation is not triggered
  * Will be addressed with #341 
- [ ] Completion of repository meta analysis can not be tracked
  * DT 4.8.0 will include various policy conditions that make this necessary in order to work
- [ ] Mirroring and ad-hoc vulnerability analysis with VulnDB is not implemented
  * See #286 
- [ ] Mirroring of GitHub Advisories is not implemented
  * The [library](https://github.com/jeremylong/vuln-tools) we use for NVD mirroring supports GHSA, too

**Comment by nscuro** [comment]
We have raised issues to track all items we identified so far. Closing this meta issue.
