### ISSUE TITLE
Support component integrity verification

### ISSUE THREAD

**Issue by mehab** [DependencyTrack/hyades#699]
This issue expands on [issue](https://github.com/DependencyTrack/dependency-track/issues/2529) in upstream dependency track. An initial POC for this has been completed and demoed using [hyades-apiserver](https://github.com/DependencyTrack/hyades-apiserver/tree/feature/integritycheckmaven) and [hyades](https://github.com/DependencyTrack/hyades/tree/mavenintegritychecpoc)
Below features need to be addressed as part of actual implementation:

```[tasklist]
### Tasks
- [ ] Allow integrity check for maven on components
- [ ] The integrity check would be enabled/ disabled universally with a single feature flag/ config in apiserver
- [ ] The meta information along with the published date and hashes would be sent back from hyades to apiserver in one message in the same topic as meta analysis result.
- [ ] When published date for a component is already present in the db, then we do not need to make the api call for it. 
- [ ] This information of component hashes and published date would be stored in a separate table. 
- [ ] This table would be used to perform hash check on components, in case info is present. If not, api call would be requested.
- [ ] Regardless of whether the integrity check is enabled/ disabled, we would fetch the information of component and store it in the db. If integrity check is enabled, the analysis would also be performed and stored. If not enabled, the analysis would not be performed
- [ ] Implement this functionality for npm and pypi as well. The initial understanding is that the source of truth used to validate integrity information uses the head request to dependency files to reveal their checksum information. This would be expanded on in the future.
- [ ] In addition to bom upload, this check should also happen on re analysis and manual addition of components.
- [ ] Project deletion should happen successfully.
- [ ] Unit tests for the entire functionality
- [ ] Future enhancement : add validation on repo URLs if integrity check can be performed on it or not.
```

**Comment by mehab** [comment]
Based on the PR review for https://github.com/DependencyTrack/hyades/pull/727 we wanted to also store the published date information from the same end point that is used to fetch integrity information for packages. 
However, as per current design, integrity check is an optional check that the user can enable/ disable for a repo of choice and then the integrity check would be performed for components considering the configured repo as the source of truth. 
This is viable for integrity checks alone. 
But published date is a field that we want for all components all the time and is not optional. Also, the repository from which the component is actually fetched should be used to get the published date for the component. Thus we cannot use the integrity check external call as is to support the published date feature.
There are a few options on how we could get publised date too:

1. Use separate repos to get published date information for packages. For example, we could use maven central to get published date for maven packages. In this case, the user can configure only one source from where the published date would be fetched. If the user does not select any source, we will use maven central. In this case, the integrity check info fetch is separate from the published date config. Can also use artifactory in this sense. 
2. Use deps.dev as the central source of truth for both integrity check and published date. In this case, allow the user to configure integrity check as currently is available. But published date is always fetched for component, if new, from deps.dev. This is not configurable by the user. 
The downside is that the published date feature is an additional call to a similar end point if it is not the same configuration as that used for integrity check. 
This is found to be part of the head request response as was done for integrity check. The header is x-modified.. to be looked for in this call.

**Comment by mehab** [comment]
**Meeting notes from discussion on September 18 2023.** 

**Use Cases**

Integrity Verification

* Detection of "smuggled" packages (Replacing of packages in the package repository)
    * Modified package was resolved from internal repo during build, and is included in SBOM
    * Comparison of package hashes from SBOM with hashes from Maven Central will yield a mismatch
* Detection of Man In The Middle’d packages
    * Bad actor replaces packages during build when package manager fetches them from repository
* Nice-to-have: There should be metrics of how many integrity violations occurred per component / project
    * Doesn’t add too much value because metrics in the UI are not used that much
* It is not necessary to configure repositories specifically for integrity checks; Use the same repository for latest version check, integrity check, published date
* Integrity check enabled/disabled should be a feature flag at first
    * When disabled, analysis and metrics inclusion would not happen
    * Fetching of the data (hashes, published date) will happen no matter if enabled or not



Multiple Repositories for integrity verification

* Being able to use Artifactory / other custom repositories
* Configuration would be priority-based, such that Maven Central can be assigned a higher priority than internal repos
    * Fall-through logic; Iterate through all repos, return on first match, otherwise proceed to next repo
* Assumption: Only a single repository should match, we only need to store results from one, and not multiple
* Future: deps.dev could be added as another repository


pkg:maven/com.citi/citi-lib → Artifactory (Internal)
pkg:maven/org.springframework/spring-core → Maven Central


Published Date

* "Component Age" policies
* Displaying published date in UI / return in REST API


dtrack.repo-meta-analysis.component

* Consumer listening for this topic will fetch:
    * Latest Version
    * Published Date
    * Hashes
* Problems:
    * Latest Version changes over time, published date and hashes (hopefully) do not
More precise details and flow to be added by @VithikaS

**Comment by VithikaS** [comment]
1. Create new table to store hashes

`
CREATE TABLE IF NOT EXISTS public."COMPONENT_METADATA"
(
    "ID" bigint NOT NULL,
    "PURL" character varying(1024) NOT NULL,
    "MD5" character varying(1024),
    "SHA1_HASH" character varying(1024),
    "SHA256_HASH" character varying(1024),
    "PUBLISHED_AT" timestamp with time zone,
    "LAST_FETCH" timestamp with time zone,
    "REPOSITORY_ID" bigint
    CONSTRAINT "COMPONENT_METADATA_PK" PRIMARY KEY ("ID")
)`

2. Create data model and queries for new table

3. Create Initialiser which will kick off update of new table with hash information and publishedAt date on application startup

<img width="1117" alt="Screenshot 2023-03-02 at 23 01 15" src="https://github.com/DependencyTrack/hyades/assets/122881935/9ff0b5c7-5279-48f7-ae6a-160504721cda">

- Check that no records exist in COMPONENT_METADATA. Select count(ID) should be 0
- If empty,  Insert into COMPONENT_METADATA table select DISTINCT purls from COMPONENT table. publish_date and hashes will be null
- Updated fetch_date and call api to get hashes information for the package type
- Repeat for all records where publish date / hashes are null

**Comment by sahibamittal** [comment]
### Task Highlights

- [ ] Create new table and queries. @sahibamittal 
- [ ] Create Initialiser. @sahibamittal 
- [ ] Hyades-apiserver changes (bom-upload dispatching event; updating new table after repo-meta analysis results). @mehab 
- [ ] Hyades-apiserver changes (perform integrity analysis if enabled and update db). 
- [ ] Changes at hyades end (repo-meta analyzer : receiving event, calling repositories, sending data back in repo-meta analysis results). @sahibamittal

**Comment by sahibamittal** [comment]
**AnalysisResult** Proto should include fields for Component Metadata

```
message AnalysisResult {
  // The component this result is for.
  Component component = 1;

  // Identifier of the repository where the result was found.
  optional string repository = 2;

  // Latest version of the component.
  optional string latest_version = 3;

  // When the latest version was published.
  optional google.protobuf.Timestamp published = 4;

  optional bool integrityMetaAvailable = 5;
  optional IntegrityMeta integrityMeta = 6;
}
```

```
message IntegrityMeta {
  optional string md5 = 1;
  optional string sha1 = 2;
  optional string sha256 = 3;
  // When the component current version last modified.
  optional google.protobuf.Timestamp currentVersionPublished = 4;
}
```

**AnalysisCommand** Proto : 

```
`
message AnalysisCommand {
  // The component that shall be analyzed.
  Component component = 1;
  bool fetch_integrity_data = 2;
  bool fetch_latest_version = 3;
}
```

Analysis Command notes:

fetch_latest_version flag → map latest_version and latest_version_published.
fetch_integrity_data flag → map current_version_published and hashes info.

1. **initializer** → [fetch_integrity_data=true, fetch_latest_version=false]
2. **bom-upload** → if integrity data doesn't exist then [fetch_integrity_data=true, fetch_latest_version=true] 
else [fetch_integrity_data=false, fetch_latest_version=true]
3. **scheduled anaysis** → [fetch_integrity_data=false, fetch_latest_version=true]

**Comment by mehab** [comment]
A point to note is the change of repository from user when he has already supplied a repository for a package type. If this happens, currently the projects/ components for which the integrity information has already been fetched will not be refreshed with new information. In order to support this feature, **keeping in mind that we only support one repository at a time for a given package and not act as mirror for multiple repositories**, we could re factor the initializer code to get triggered on whenever the user changes repository url and refresh information for all the existing components. 
And then newer projects and components can be filled for information as existing functionality

**Comment by mehab** [comment]
the changes have now been completed hence closing the issue
